server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

spring:
  security:
    oauth2:
      client:
        registration:
          test-client-oidc:
            provider: spring
            client-id: test-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: test-client-oidc
          test-client-authorization-code:
            provider: spring
            client-id: test-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: test.read
            client-name: test-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000