server:
  port: 9000

spring:
  datasource:
    url: jdbc:mariadb://localhost/test?autoReconnect=true&tcpKeepAlive=true
    jdbc-url: ${spring.datasource.url}
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

    hikari:
      transaction-isolation :
      idleTimeout: 300000
      maxLifetime: 3600000
      maximumPoolSize: 5
      minimumIdle: 1
      poolName: test
      registerMbeans: false
      leakDetectionThreshold: 30000

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        #  sql debugging values
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO